# Improved Training Configuration for Raadha - Your Friendly Bestie

# Model Configuration
model:
  base_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  max_length: 2048
  padding: true
  truncation: true

# LoRA Configuration - Increased capacity for better adaptation
lora:
  r: 32  # Increased from 16
  alpha: 64  # Increased from 32
  dropout: 0.1  # Increased from 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]  # Added more target modules
  bias: "none"
  task_type: "CAUSAL_LM"

# Training Parameters - Optimized for better results
training:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 1e-4  # Reduced from 2e-4 for more stable training
  num_train_epochs: 5  # Increased from 3
  warmup_ratio: 0.1  # Increased from 0.03
  weight_decay: 0.01
  logging_steps: 10
  save_steps: 50  # More frequent checkpoints
  eval_steps: 50  # More frequent evaluation
  save_total_limit: 3
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "loss"

# Data Configuration - Using augmented dataset
data:
  train_file: "data/augmented/train_augmented.json"  # Using augmented training data
  eval_file: "data/augmented/eval_augmented.json"    # Using augmented evaluation data
  max_samples: null  # Set to null for full dataset

# Output Configuration
output:
  output_dir: "models/raadha-lora-improved"  # New output directory
  logging_dir: "logs/improved"  # New logging directory

# Hardware Configuration
hardware:
  fp16: false  # Disabled for MPS 