# Training Configuration for Raadha - Your Friendly Bestie

# Model Configuration
model:
  base_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  max_length: 256
  padding: true
  truncation: true

# LoRA Configuration
lora:
  r: 2
  alpha: 4
  dropout: 0.05
  target_modules: ["q_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

# Training Parameters
training:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32
  learning_rate: 1e-3
  num_train_epochs: 1
  warmup_ratio: 0.005
  weight_decay: 0.001
  logging_steps: 50
  save_steps: 500
  eval_steps: 500
  save_total_limit: 1
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "loss"

# Data Configuration
data:
  train_file: "data/train.json"
  eval_file: "data/eval.json"
  max_samples: 1000

# Output Configuration
output:
  output_dir: "models/raadha-lora"
  logging_dir: "logs"

# Hardware Configuration
hardware:
  fp16: false
  bf16: false
  gradient_checkpointing: true
  optim: "adamw_torch"
  use_cpu: true 